apiVersion: v1
kind: BuildConfig
metadata:
  name: custom-jenkins-build
spec:
  source:
    git:
      uri: https://github.com/ianff/customized-jenkins.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: DockerImage
        name: registry.access.redhat.com/openshift3/jenkins-2-rhel7:v3.11.154-1
    type: Source
  output:
    to:
      kind: ImageStreamTag
      name: custom-jenkins:latest